latitude: -10.0
longitude: 20.0
input_device_name: default

# Logging configuration
# LOG_LEVEL options: DEBUG, INFO, WARNING, ERROR, CRITICAL
# Default: INFO
log_level: INFO
# LOG_FORMAT: Custom log format string
# Default: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
# log_format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
